print("===================================================================")
print("WELCOME TO THE CUSTOM VECHICLE CHOOSER")
print("===================================================================")
print()


print("Please select the type of vehicle you want to choose from the following options:")
print("1. Car")
print("2. Truck")
print("3. Motorcycle")
print("4. Bicycle")
print("5. Bus")
print("6. Van")
print("7. Scooter")
print("8. ATV (All-Terrain Vehicle)")
print("9. RV (Recreational Vehicle)")
print("10. Electric Vehicle")
print("11. Hybrid Vehicle")
print("12. Sports Car")
print("13. Luxury Vehicle")
print("14. Off-Road Vehicle")
print("15. Classic Car")
print("16. Pickup Truck")

choice = int(input("Enter the number corresponding to your choice (1-16): "))
print()

if choice == 1:
    print("You have chosen a Car.")
    print("pick a car from the following options:")
    print("1. Sedan")
    print("2. Hatchback")
    print("3. Coupe")
    print("4. Convertible")
    car_choice = int(input("Enter the number corresponding to your choice (1-4): "))
    if car_choice == 1:
        print("You have chosen a Sedan.")
        print("Sedans are known for their comfortable ride and spacious interiors.")
        print("They are ideal for families and long-distance travel.")
        print("Some popular sedan models include the Toyota Camry, Honda Accord, and BMW 3 Series.")
        print("Sedans typically have four doors and a separate trunk for storage.")
        print("They offer a balance of performance, fuel efficiency, and practicality.")
    elif car_choice == 2:
            print("You have chosen a Hatchback.")
            print("Hatchbacks are compact cars with a rear door that swings upward to provide access to the cargo area.")
            print("They are known for their versatility and fuel efficiency.")
            print("Some popular hatchback models include the Volkswagen Golf, Ford Focus, and Honda Fit.")
            print("Hatchbacks often have a sporty appearance and are great for city driving.")
            print("They offer a good balance of passenger space and cargo capacity.")
    elif car_choice == 3:
            print("You have chosen a Coupe.")
            print("Coupes are two-door cars that are known for their stylish design and sporty performance.")
            print("They are often associated with luxury and high-performance vehicles.")
            print("Some popular coupe models include the Ford Mustang, Chevrolet Camaro, and BMW 4 Series.")
            print("Coupes typically have a sleek and aerodynamic shape, making them visually appealing.")
    elif car_choice == 4:
            print("You have chosen a Convertible.")
            print("Convertibles are cars with a retractable roof that can be opened or closed.")
            print("They offer an exhilarating driving experience, especially in good weather.")
            print("Some popular convertible models include the Mazda MX-5 Miata, Ford Mustang Convertible, and BMW Z4, and discountined BMW I8 Roadster.")
            print("Convertibles are often associated with luxury and leisure driving.")
elif choice == 2:
        print("You have chosen a Truck.")
        print("Trucks are known for their towing capacity and cargo space.")
        print("They are ideal for transporting goods and heavy loads.")
        print("Some popular truck models include the Ford F-150, Chevrolet Silverado, and Ram 1500.")
        print("Trucks often have a robust build and are designed for durability and performance.")
elif choice == 3:
        print("You have chosen a Motorcycle.")
        print("Motorcycles are two-wheeled vehicles that offer a thrilling riding experience.")
        print("They are known for their agility and fuel efficiency.")
        print("Some popular motorcycle models include the Harley-Davidson Street Glide, Yamaha YZF-R1, and Honda CBR600RR.")
        print("Motorcycles come in various styles, including cruisers, sport bikes, and touring bikes.")
elif choice == 4:
        print("You have chosen a Bicycle.")
        print("Bicycles are human-powered vehicles that are great for exercise and eco-friendly transportation.")
        print("They come in various types, including road bikes, mountain bikes, and hybrid bikes.")
        print("Some popular bicycle brands include Trek, Specialized, and Giant.")
        print("Bicycles are an excellent choice for short commutes and recreational riding.")
elif choice == 5:
        print("You have chosen a Bus.")
        print("Buses are large vehicles designed to carry multiple passengers.")
        print("They are commonly used for public transportation and long-distance travel.")
        print("Some popular bus models include the Mercedes-Benz Citaro, Volvo 7900, and New Flyer Xcelsior.")
        print("Buses come in various sizes, including city buses, coach buses, and double-decker buses.")
elif choice == 6:
        print("You have chosen a Van.")
        print("Vans are versatile vehicles that can be used for transporting passengers or cargo.")
        print("They are often used by businesses for deliveries and by families for road trips.")
        print("Some popular van models include the Ford Transit, Mercedes-Benz Sprinter, and Honda Odyssey.")
        print("Vans come in various configurations, including minivans, cargo vans, and passenger vans.")
elif choice == 7:
        print("You have chosen a Scooter.")
        print("Scooters are small, lightweight vehicles that are easy to maneuver in urban environments.")
        print("They are known for their fuel efficiency and convenience.")
        print("Some popular scooter models include the Vespa Primavera, Honda PCX, and Yamaha NMAX.")
        print("Scooters are ideal for short commutes and city travel.")
elif choice == 8:
        print("You have chosen an ATV (All-Terrain Vehicle).")
        print("ATVs are designed for off-road use and can handle rough terrain.")
        print("They are popular for recreational activities such as trail riding and racing.")
        print("Some popular ATV models include the Polaris Sportsman, Yamaha Raptor, and Can-Am Outlander.")
        print("ATVs come in various sizes and configurations, including two-wheel drive and four-wheel drive models.")
elif choice == 9:
        print("You have chosen an RV (Recreational Vehicle).")
        print("RVs are motorized vehicles that provide living accommodations for travel and camping.")
        print("They come in various types, including motorhomes, travel trailers, and camper vans.")
        print("Some popular RV brands include Winnebago, Airstream, and Thor Motor Coach.")
        print("RVs offer the convenience of home on the road, with amenities such as kitchens, bathrooms, and sleeping areas.")
elif choice == 10:
        print("You have chosen an Electric Vehicle.")
        print("Electric vehicles (EVs) are powered by electricity and produce zero emissions.")
        print("They are known for their quiet operation and low running costs.")
        print("Some popular electric vehicle models include the Tesla Model 3, Nissan Leaf, and Chevrolet Bolt EV.")
        print("EVs come in various body styles, including sedans, SUVs, and hatchbacks.")
elif choice == 11:
        print("You have chosen a Hybrid Vehicle.")
        print("Hybrid vehicles combine an internal combustion engine with an electric motor for improved fuel efficiency.")
        print("They are known for their reduced environmental impact and lower fuel consumption.")
        print("Some popular hybrid vehicle models include the Toyota Prius, Honda Insight, and Ford Fusion Hybrid, and discountined BMW I8.")
        print("Hybrids come in various body styles, including sedans, SUVs, and hatchbacks.")
elif choice == 12:
        print("You have chosen a Sports Car.")
        print("Sports cars are designed for high performance and agility.")
        print("They are known for their sleek design and powerful engines.")
        print("Some popular sports car models include the Porsche 911, Chevrolet Corvette, and Ford Mustang, and BMW M Series.")
        print("Sports cars often have two doors and a low profile, making them visually striking.")
elif choice == 13:
        print("You have chosen a Luxury Vehicle.")
        print("Luxury vehicles are known for their premium features, comfort, and advanced technology.")
        print("They offer a high level of craftsmanship and attention to detail.")
        print("Some popular luxury vehicle brands include Mercedes-Benz, BMW, Audi, and Lexus.")
        print("Luxury vehicles come in various body styles, including sedans, SUVs, and coupes.")
elif choice == 14:
        print("You have chosen an Off-Road Vehicle.")
        print("Off-road vehicles are designed to handle rough terrain and challenging driving conditions.")
        print("They are often equipped with features such as four-wheel drive, high ground clearance, and rugged tires.")
        print("Some popular off-road vehicle models include the Jeep Wrangler, Toyota Land Cruiser, and Land Rover Defender.")
        print("Off-road vehicles are ideal for outdoor adventures and exploring remote areas.")
elif choice == 15:
        print("You have chosen a Classic Car.")
        print("Classic cars are vintage vehicles that are often prized for their historical significance and unique design.")
        print("They are typically well-maintained and restored to preserve their original condition.")
        print("Some popular classic car models include the Ford Mustang (1960s), Chevrolet Bel Air, and Volkswagen Beetle.")
        print("Classic cars are often showcased at car shows and events, attracting enthusiasts and collectors.")
elif choice == 16:
        print("You have chosen a Pickup Truck.")
        print("Pickup trucks are versatile vehicles that combine passenger comfort with cargo-carrying capability.")
        print("They are known for their towing capacity and off-road performance.")
        print("Some popular pickup truck models include the Ford F-150, Chevrolet Silverado, and Ram 1500.")
        print("Pickup trucks come in various configurations, including single cab, extended cab, and crew cab options.")


        
